[package]
name = "webify"
version = "0.1.0"
authors = ["thomasfire <thomasfire@yandex.ru>"]
edition = "2018"

[dependencies]
actix-web = "1.0.*"
actix-identity = "0.1.*"
actix-form-data = "0.4.*"
actix-multipart = "0.1.*"
toml = "0.5"
serde_derive = "1.0.*"
serde_json = "1.0"
serde = "1.0.*"
diesel = { version = "1.4.3", features = ["sqlite", "r2d2", "chrono"] }
chrono = "0.4.*"
futures = "0.1.*"
rust-crypto = "0.2.*"
rand = "0.7.2"
flate2 = "1.0"