[package]
name = "webify"
version = "0.1.0"
authors = ["thomasfire <thomasfire@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
toml = "0.5"
serde_derive = "1.0.*"
serde_json = "1.0"
serde = "1.0.*"
diesel = { version = "1.4.*", features = ["sqlite", "r2d2"] }
chrono = "0.4.*"